[[snappy]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "59a9ff0a54fe9ac93d86c584182a7f1e8b0e938a"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "a8e82c35f6933180a245584bd272a3437f387d6b322ff0eeeeec556c2c1e0681"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.8+1/snappy.v1.1.8.aarch64-linux-gnu-cxx03.tar.gz"
[[snappy]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57880a41c4c38272d15ffadf4ca6c5dfebb5cf61"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "eaff4d933982ee930e488227723bd82534d63bbaeac1148e18b67f82558c6e00"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.8+1/snappy.v1.1.8.aarch64-linux-gnu-cxx11.tar.gz"
[[snappy]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3370e435a5bf2e47e489d1a6ef8dbb82ea14f3fb"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "aa50ab7e5b95dc91b343862859b4bcd05db7510a3a6eb13ee8abbbddbff9d41b"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.8+1/snappy.v1.1.8.aarch64-linux-musl-cxx03.tar.gz"
[[snappy]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "93527cf5eef63741f2faf51a52d3d80b3acd0d8d"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "1315b7b956cc095b604e2fda1aa4bdf8ec15a65e7b40a153dedb5600f7c4ba05"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.8+1/snappy.v1.1.8.aarch64-linux-musl-cxx11.tar.gz"
[[snappy]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7566b129abf92c96a5d2ba0c3266a21303182afc"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "d1ff91feba5c0609694be8f211601a0500ce2c72019e6a8c4ac74250871f5ddf"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.8+1/snappy.v1.1.8.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[snappy]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11d5f037c152b59ee53cfb57901265c445ffd536"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "07b78830818bc1e9789d21df6a61d5eafcd1e5bac746e047acdc4e9fba5e02ca"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.8+1/snappy.v1.1.8.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[snappy]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "07c5b30cc8afd12907328f12451ded8e36a18aae"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "829fb2876e12f6f661e5e3e2aefee022e4fb89411fcaba9ee40b1f9d7a0bd35e"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.8+1/snappy.v1.1.8.armv7l-linux-musleabihf-cxx03.tar.gz"
[[snappy]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a27fd38b9db494b3318cb2af39a26b1632b187fe"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "48b22c267fef15e1fcd7cf6a0d7b5335a0002c912bbac595b21da65b8acc275e"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.8+1/snappy.v1.1.8.armv7l-linux-musleabihf-cxx11.tar.gz"
[[snappy]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc99042e2c7023960f256853ac0cd7377faf46b0"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "71b1b228ca7eef8ca204b8535c0335736c11e8b0091bee55a047e07d49d2fd8a"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.8+1/snappy.v1.1.8.i686-linux-gnu-cxx03.tar.gz"
[[snappy]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd3002be4a3f1a28aaf947e2c235ad6d1155d461"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "691df13a42d2d43dbd3683e341895e16fa07ebb964dafccd61c12be17323fcc2"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.8+1/snappy.v1.1.8.i686-linux-gnu-cxx11.tar.gz"
[[snappy]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4c5c1d474169cab7e69f21a344f523ed4e3f351d"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "22480b19fe85ce6ad3ae3ed135ccb5be9db01d9280c94d46696449c5d22ead29"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.8+1/snappy.v1.1.8.i686-linux-musl-cxx03.tar.gz"
[[snappy]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a41afc5582ce893316b8b4fb26c5daa5dce91e07"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "265f9d46565bd7595f79913e2594c8fe2c26647017dfd0656fb39f983551ae4b"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.8+1/snappy.v1.1.8.i686-linux-musl-cxx11.tar.gz"
[[snappy]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "42055e6d63814871ec334460f7c84cc0cd71e52b"
os = "windows"

    [[snappy.download]]
    sha256 = "800f9dd9dca6bffa11dee4b5407936973f2f1018b5d4eb5471b287c9872de660"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.8+1/snappy.v1.1.8.i686-w64-mingw32-cxx03.tar.gz"
[[snappy]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a56648ac6b24b687d6e0626d5e42c863ecf40b9a"
os = "windows"

    [[snappy.download]]
    sha256 = "3f2aae04e257fa6d869e60cb28aaaf16ff6f98daddcdfd5522e6f55b82cbc053"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.8+1/snappy.v1.1.8.i686-w64-mingw32-cxx11.tar.gz"
[[snappy]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dfcbc93d01f65abb7b63b282aac8c45f62fb7af1"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "1f94faa3549f0d284d84d75ec745db58370770ab860f362bb84af0bbfd193e6d"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.8+1/snappy.v1.1.8.powerpc64le-linux-gnu-cxx03.tar.gz"
[[snappy]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f043cb1a031621c2e7b1e9dbb77c97b84a09eb0f"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "7a87781baecea09548cfaef11ccd49af9ad8cc1bd00c33bad42c074a291d97fd"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.8+1/snappy.v1.1.8.powerpc64le-linux-gnu-cxx11.tar.gz"
[[snappy]]
arch = "x86_64"
git-tree-sha1 = "d5500fcab20b2547ee1096dea250fcee97cd35df"
os = "macos"

    [[snappy.download]]
    sha256 = "c2f7b3c9dedf1971823e841f6779f6cd306baad8e1f27e4a3fffdc30ff8659de"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.8+1/snappy.v1.1.8.x86_64-apple-darwin.tar.gz"
[[snappy]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c3cd4ac38ad309defc5d5c80b5b3e19b7b887d3c"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "9e17f125fe39a29abfb8b0dfff14df2dcc4339522057157570c99af07d80502c"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.8+1/snappy.v1.1.8.x86_64-linux-gnu-cxx03.tar.gz"
[[snappy]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "893191ce25beaf9409ef3717ff7b6e38d11a4a7f"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "24e38c0e5e8c2ae35779be8f7d314f74aa83c6ef180e7837ec61364e8231e855"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.8+1/snappy.v1.1.8.x86_64-linux-gnu-cxx11.tar.gz"
[[snappy]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a0890d319ecdbb19c925296c18a8dba5d61db343"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "c322b49b925d795d03571d23923354ee7a1f67adfdbdb6954634d1ca2e33f415"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.8+1/snappy.v1.1.8.x86_64-linux-musl-cxx03.tar.gz"
[[snappy]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b67603c54d8d8af9f0a247e21340124707f846c2"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "82942ae0c8e016f378db917f873db39e8df3186b5f087f07c4bd220e3941ea3f"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.8+1/snappy.v1.1.8.x86_64-linux-musl-cxx11.tar.gz"
[[snappy]]
arch = "x86_64"
git-tree-sha1 = "f7a76f60591f086afd4c64a76e3f774165c55c6f"
os = "freebsd"

    [[snappy.download]]
    sha256 = "7f81328aa1f075e2652eb40953c183fafd602e8c319f03d8826401c965a6167d"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.8+1/snappy.v1.1.8.x86_64-unknown-freebsd.tar.gz"
[[snappy]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6245ffb813257968ab4ec8b8e80400614f7564d9"
os = "windows"

    [[snappy.download]]
    sha256 = "83160032b3a7cf683d324134ed8fc7f676d7cb4c52832104f27904b721c40a2c"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.8+1/snappy.v1.1.8.x86_64-w64-mingw32-cxx03.tar.gz"
[[snappy]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b93d3af8746341ab0ea2f0a53d7c2c50a788539d"
os = "windows"

    [[snappy.download]]
    sha256 = "1086855bc7b39ac558534c5ea0e94b20920e13ce68e87ea277aa64b4d8a4466c"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.8+1/snappy.v1.1.8.x86_64-w64-mingw32-cxx11.tar.gz"
