[[snappy]]
arch = "aarch64"
git-tree-sha1 = "04dc210a0f06a7799da3fd7c1e76ef47f2b28e92"
os = "macos"

    [[snappy.download]]
    sha256 = "aa56eb687b512b9f8f1e791c080604e6612349e72dabcd9e063d269fe059f971"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.9+1/snappy.v1.1.9.aarch64-apple-darwin.tar.gz"
[[snappy]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "433c4abee85dabf54605b33df12b48cb02621302"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "2c19831509b92d74f4697f932167a3ffb3f13b797d257d52fcd7c6b3ac2a96e4"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.9+1/snappy.v1.1.9.aarch64-linux-gnu-cxx03.tar.gz"
[[snappy]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9904f0a1f5774b13dcd80233e43a68d530eddd21"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "b41e044a1cf10cb82cc12b722c295b610d022c08d77fb8b0e1aa1972bbc469d5"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.9+1/snappy.v1.1.9.aarch64-linux-gnu-cxx11.tar.gz"
[[snappy]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aa7dfd5bba4415f455976dd67d66d09f3510a4a4"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "14244d2aed68937e933c21108bea494b13f26cdc0d42c97f6202221f78b10510"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.9+1/snappy.v1.1.9.aarch64-linux-musl-cxx03.tar.gz"
[[snappy]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f767d224511beb07f01983e75338160f8f5eed8c"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "65d0a95937d4ad81b7076c047d736474ed3934488d6bccddd6882f56a9a22fb2"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.9+1/snappy.v1.1.9.aarch64-linux-musl-cxx11.tar.gz"
[[snappy]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b82fc99a017d7c016c4659629af7d9d757750e74"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "e9779f8d65240cbfbd75d6a2c9b3af6d66bee785b013ddb642b927614a316b1a"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.9+1/snappy.v1.1.9.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[snappy]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "14127ebc93395e8dd85a61ef7128d2e34d400847"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "87c1556895079e573b10ab31494f7577803c184291bb0037932bf64cbdad1f15"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.9+1/snappy.v1.1.9.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[snappy]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e7f2346fbca3e046c5bf85e3c7ac01b6f17a0ea3"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "7811b0618da901ed1dec86c48016dc768282e8da687385a8687c32d6a354460c"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.9+1/snappy.v1.1.9.armv6l-linux-musleabihf-cxx03.tar.gz"
[[snappy]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e9fafdb748729385870d4342fa5230db5b25be99"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "6f114178564f7fb937d496ca8e94265661723d42964c919cea0279b5f63618b1"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.9+1/snappy.v1.1.9.armv6l-linux-musleabihf-cxx11.tar.gz"
[[snappy]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4eb6533790ce02c9fc6d9d55055028687a57f932"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "605485d29604dd6f3d11175bf77ab41ddf2a111b6e24f1e6e3040f449015d49d"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.9+1/snappy.v1.1.9.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[snappy]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9dd832934dbb212b066fe78dceb03742cf6aa025"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "b20322167299657e1dfb0da989b3a546cf6963911f32b3e5a7714932a4ddb727"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.9+1/snappy.v1.1.9.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[snappy]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7f4bd84c91a8fdcac98e1a645e83d5ed543ca609"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "0c15e2b3a33a690ccdfecf2ed94574e99fe24166f8130ac58ac7db29687f355f"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.9+1/snappy.v1.1.9.armv7l-linux-musleabihf-cxx03.tar.gz"
[[snappy]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eddda2fc0037d8ae591758869c705001b1822fd7"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "a767e2972c8aceaa7e3644f079db1e9e638f8264c1713323911a7205d8db66f1"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.9+1/snappy.v1.1.9.armv7l-linux-musleabihf-cxx11.tar.gz"
[[snappy]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3ab8d1647db55c04e07898bd10ec568d0812ba27"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "0279ad5d55bf1b8a6ab5ee4d83610d9d37b3f9a6f46412e4cdaeddc3afcffd88"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.9+1/snappy.v1.1.9.i686-linux-gnu-cxx03.tar.gz"
[[snappy]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f877f0a86f1e78e019c8e388c57f6561e587a4e"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "5f96f527a570c969bdf6cdf62bf372239d7e58144ab221b42a1871a7bb4bdd39"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.9+1/snappy.v1.1.9.i686-linux-gnu-cxx11.tar.gz"
[[snappy]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "163b98eaadec88a597bd191dd0c1f394dfbbd8a8"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "993c476204b23b52e091608b1230b2463d05f856162bfd48c247a54308cc653f"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.9+1/snappy.v1.1.9.i686-linux-musl-cxx03.tar.gz"
[[snappy]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd9dc7050e0b85f5ec5f2ef35363fde720fb46df"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "f6bf81e013d6bd41d956b46375f98e23570e4f489a7addf0fe86bdb0aed09721"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.9+1/snappy.v1.1.9.i686-linux-musl-cxx11.tar.gz"
[[snappy]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8f65b4441891a8cf7bb4b15cefb8d71a192b30fa"
os = "windows"

    [[snappy.download]]
    sha256 = "3e318d1797034142b0eb7a9ad85d271ded097dfe769b94a7e24440754cbc5251"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.9+1/snappy.v1.1.9.i686-w64-mingw32-cxx03.tar.gz"
[[snappy]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1312096d33b369e5df70c0a21030fd8fa694f457"
os = "windows"

    [[snappy.download]]
    sha256 = "fd2e0bb2d4a2512eb46c2c9f7c0f8892734baf716c5291d8a85d10b1472f9875"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.9+1/snappy.v1.1.9.i686-w64-mingw32-cxx11.tar.gz"
[[snappy]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9877c9e4469d47c56c9272372ea8d500d8d0d03b"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "82abe0b1046ec63b07b7627e863f111c33544d73d987a8000bb4ed203c0f1be8"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.9+1/snappy.v1.1.9.powerpc64le-linux-gnu-cxx03.tar.gz"
[[snappy]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be0ce25b7623deb77a423a62d330b98bf022a1a4"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "64319820d207c78de8e579232af8814393980df6005db8db16458a30852973e7"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.9+1/snappy.v1.1.9.powerpc64le-linux-gnu-cxx11.tar.gz"
[[snappy]]
arch = "x86_64"
git-tree-sha1 = "5fd53a64cb905a0f820a687591279b3eea0da490"
os = "macos"

    [[snappy.download]]
    sha256 = "3f3a31d4674dc27ba84f0106f7eecca396225835d2e542a4829bc728da807ad2"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.9+1/snappy.v1.1.9.x86_64-apple-darwin.tar.gz"
[[snappy]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9fc9aa76cda530eaa0d931990d2ba9f1dfd40ac9"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "c14b7f2fa5e15cc72376f5ac1ba079a766279c36682b8e0854ff1b7ecce3dc45"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.9+1/snappy.v1.1.9.x86_64-linux-gnu-cxx03.tar.gz"
[[snappy]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "05596eec83a73680afa608b06b8a7fe56dfbcb57"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "beb2ffba2263258c2c4d69ae3122a3f6da1484784d739868e5faa0a046cab38f"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.9+1/snappy.v1.1.9.x86_64-linux-gnu-cxx11.tar.gz"
[[snappy]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "faee219c19bbcb0c1a9d19528c9a4665c184b783"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "7b3a515510296fde36eb8a0763ab36e0e05bc5c00efd5209ff85234fc60cf6c3"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.9+1/snappy.v1.1.9.x86_64-linux-musl-cxx03.tar.gz"
[[snappy]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c9b1428b6094350d0f1262d715f4e0ca852fde29"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "27b297518c4bd0faa938f411c8de316f00eec193bbd8798e23afe9d1e19141c6"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.9+1/snappy.v1.1.9.x86_64-linux-musl-cxx11.tar.gz"
[[snappy]]
arch = "x86_64"
git-tree-sha1 = "255b301b9d7ae297bec0fcf5b87dff381dbb1657"
os = "freebsd"

    [[snappy.download]]
    sha256 = "b1f63dda3d6e440d3cbddeb912fcc700b7bb72d5b2d782b468bf2a185a578336"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.9+1/snappy.v1.1.9.x86_64-unknown-freebsd.tar.gz"
[[snappy]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fe0c03e8e7dc7c16fd0948b95bd9c64f64de0cab"
os = "windows"

    [[snappy.download]]
    sha256 = "3a792e8a7366a9aabb0e027f0e8690770d47ec88e6f1eb2e5fa1e6df92d52c1a"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.9+1/snappy.v1.1.9.x86_64-w64-mingw32-cxx03.tar.gz"
[[snappy]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a214c5171a32bff0583c70a08027d44e8ef22cc2"
os = "windows"

    [[snappy.download]]
    sha256 = "06a3e4188222e4325237d173c5caa6961c2847ba2c9a4573682fcab2f8d7e77a"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.1.9+1/snappy.v1.1.9.x86_64-w64-mingw32-cxx11.tar.gz"
