[[snappy]]
arch = "aarch64"
git-tree-sha1 = "7d028156aa00e80f21ebf42a3ca5fd9aa3e5f982"
os = "macos"

    [[snappy.download]]
    sha256 = "a8f9df9a4c240d4c1bbf382c39c27f1be786a2ec85ef7a47f71bbd37ea5c9ecc"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.0+0/snappy.v1.2.0.aarch64-apple-darwin.tar.gz"
[[snappy]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aa3bccbfd6194ab9b7feac301c1637e9ac1f3f04"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "dd3acab02a0d6f68048573d48567fdce89421f900de8124305b188e471004b13"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.0+0/snappy.v1.2.0.aarch64-linux-gnu-cxx03.tar.gz"
[[snappy]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e27f0549bea8748b986e1456742a6a4481fb5747"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "2b16f813d631c6ee2f22112bcd4556a77ceb8d59d816692d5b748cc40cc22a4c"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.0+0/snappy.v1.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[snappy]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b2c46db26902c612681ec67fb1d56caac8da0b25"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "4cb3b97799ea1d1e21134393136e7047d9793337bd88806496eda47a287340b5"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.0+0/snappy.v1.2.0.aarch64-linux-musl-cxx03.tar.gz"
[[snappy]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f81b3e5fb60f8ca777df6c685d91e261b75a8d83"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "e005b492c50588a6722b8521dd163ff87fd3ee7b8518ef70ef3d2772bc3d4010"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.0+0/snappy.v1.2.0.aarch64-linux-musl-cxx11.tar.gz"
[[snappy]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f5472c8abc2228e0a6c31d22a20ebd2c6827efa7"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "36ab6c6bde5f56ef85d11fd685278cefa2979453779945dea3329be75cf37ec0"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.0+0/snappy.v1.2.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[snappy]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd7a71c9a335683236cd9cc80ac9297a4824df23"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "d5f3f0b9e552d6cd7938667fbcf93bab6366cd0e2d22e8c5441d4adbac3c8647"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.0+0/snappy.v1.2.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[snappy]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5dc7d80db5e5a83f32bd8830d2661312878676ee"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "c5cbaf1806a27070c15092ab85b37bcd5d8660df351f6a2ef5dc6ec21c471924"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.0+0/snappy.v1.2.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[snappy]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3582641444650ef89d558c5de30d45d05cb8b32e"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "c8525512affc1430726094528b7f5a1dd3e1a07317bed8c8cabea401fc597739"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.0+0/snappy.v1.2.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[snappy]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0e2beab2bc47eb55cff071445f7f41b3a402f385"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "c22fba7134ca2278b7abb223f65ddf06969096dc3298e7252c2e9974f73cfc33"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.0+0/snappy.v1.2.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[snappy]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d4cd17d301832c2df441ca391923f6140407735a"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "0fc3ab17c70cfac4b10377ce41ff1aa000a951a8ef30c65d9c75cb3313f0ec54"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.0+0/snappy.v1.2.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[snappy]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "df84f3ee5fbe322d0e4aa4265846fcc47f448809"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "2721c01311204736b7b252f62a1ffb5a7ac4e9e5ba545a9230432d9fd26889bc"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.0+0/snappy.v1.2.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[snappy]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e3f95828956d3b7da2c30636848f04bec5be8eb"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "250edf23641eca62d39f81ca60bbf1eebadce7382f78bb9e9dc8bf9796fe56d2"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.0+0/snappy.v1.2.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[snappy]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "208fce7ae2e2f510c6236e67fcbf0a8f5171124d"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "b746cd7b3cdd45f5ce1e95fe2f44c7e1c27e9e99576725900afe5da4fabae065"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.0+0/snappy.v1.2.0.i686-linux-gnu-cxx03.tar.gz"
[[snappy]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c91fc580231870348156e49540897500a8e0096b"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "d8785cccea2551127f6d5811d6275ad6b582afc4c4da29bd786bbad0e25cb10a"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.0+0/snappy.v1.2.0.i686-linux-gnu-cxx11.tar.gz"
[[snappy]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e78393692759f60ab23881b063ac76c4a0bae80e"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "4842c5e5a9c0cc97e40f68b700b84e861ed93c2ec525ce247d930f76e3b5c22e"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.0+0/snappy.v1.2.0.i686-linux-musl-cxx03.tar.gz"
[[snappy]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a4cd8fb65b6a01d2b0af1420f40ca77258bf5e2d"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "50f4607b9ee907b1afd6b8b51145addad7fd445cc8bd386b27a326e63e79d708"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.0+0/snappy.v1.2.0.i686-linux-musl-cxx11.tar.gz"
[[snappy]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0d1e109e32a3d132a3002839ee8e96f7d0cdd164"
os = "windows"

    [[snappy.download]]
    sha256 = "0a28a95119a0eaa0ba2cf58434badfa42c13b81e4e6f8044478c72d95e06f75c"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.0+0/snappy.v1.2.0.i686-w64-mingw32-cxx03.tar.gz"
[[snappy]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "406f64c253868f4919779c35121aa9632edab931"
os = "windows"

    [[snappy.download]]
    sha256 = "4cfa225f77eb96adb1b168d03693d9d89cb922810edde6c53ee68e5f3a0ad726"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.0+0/snappy.v1.2.0.i686-w64-mingw32-cxx11.tar.gz"
[[snappy]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ffa9424b656dff67df9a36206ea2b56604b0ca68"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "3b7d19b9c71989663f491fa16bb5a46d2d68be93a78a19d3efceca050d8772ad"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.0+0/snappy.v1.2.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[snappy]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5866f26234bee0cedb3926b0ad0bac24aba0fdf8"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "dac2343c68442827cbda5d62417a5349319bfb8c9e97e864bc47f2ac066b8e70"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.0+0/snappy.v1.2.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[snappy]]
arch = "x86_64"
git-tree-sha1 = "cbf813a9c36d3047e970fc7e12a258f976ad7487"
os = "macos"

    [[snappy.download]]
    sha256 = "4d3620f725a4f52712bdd443d4a5516f5142753cc2a291c46f09202506168f82"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.0+0/snappy.v1.2.0.x86_64-apple-darwin.tar.gz"
[[snappy]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ec80ffd99754bf1db2d452b529c6334d6efb224c"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "4e6948de01c2b194b93ac5fad06f87dc5ec05c1380999962c00a53b424f89a3c"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.0+0/snappy.v1.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[snappy]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf9b34237d4aa7ebbaf2aa5a4598c313147e459b"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "211ca509912e804407d9f51c3653cdf1b24339593c17098624ffaf576a7cc7df"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.0+0/snappy.v1.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[snappy]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e47481bb491b5a4991ed38eb4971382834621db6"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "fca5c11fa53a8e8088ae525993bd3cab3bff25936668076b31ee6f3304cb0285"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.0+0/snappy.v1.2.0.x86_64-linux-musl-cxx03.tar.gz"
[[snappy]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f44faeaea18a4353e428143cd6c385f5c35df28"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "55f88f840b7b583b102a9438df433f1bd0ef50b8f85e17135cc13b9b02bf1a61"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.0+0/snappy.v1.2.0.x86_64-linux-musl-cxx11.tar.gz"
[[snappy]]
arch = "x86_64"
git-tree-sha1 = "25691aea5c08a9e470b9cb98bea891a0421c3653"
os = "freebsd"

    [[snappy.download]]
    sha256 = "41605615484a16ba0385a180ca457b34be54b6a1ade1e4454aaa3b574f7adaa6"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.0+0/snappy.v1.2.0.x86_64-unknown-freebsd.tar.gz"
[[snappy]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1f4731311b9e9edd8164ec85b1354a2d2ff5bfba"
os = "windows"

    [[snappy.download]]
    sha256 = "03e66555c1ed6169029d807f3df92a13b03f08efb0935c14b3a40df339656b7f"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.0+0/snappy.v1.2.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[snappy]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c6335af11f5fd345b371665c1b1462e74c9afbc"
os = "windows"

    [[snappy.download]]
    sha256 = "6816caf5327defcba01f4d8197ce04269989a1ad457a9ee75d845882dbfe10fd"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.0+0/snappy.v1.2.0.x86_64-w64-mingw32-cxx11.tar.gz"
