[[snappy]]
arch = "aarch64"
git-tree-sha1 = "a591a2c609dc52c1832d01ad3a438d7327238ec7"
os = "macos"

    [[snappy.download]]
    sha256 = "ae57630073d23bcd0d7caf2799bccef5efec81a5a25d5d0b2d32fb2d17d2c729"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.2+0/snappy.v1.2.2.aarch64-apple-darwin.tar.gz"
[[snappy]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0f4fe72a227d553ed6caf127821be8da3a996860"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "f50ae8ea69825cdd81c8f7de7058a124abb3331687676f5b342b0a9aba5f82cc"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.2+0/snappy.v1.2.2.aarch64-linux-gnu-cxx03.tar.gz"
[[snappy]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "49340d00996af610b86b6f9c0a3c627dcd4394f6"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "0b2c96d08f627d09662484aaaedfe2fb5a3b65ed3574fc56417143e3a2d91912"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.2+0/snappy.v1.2.2.aarch64-linux-gnu-cxx11.tar.gz"
[[snappy]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9355d83fb366c7d157c0036efdaa6fa47b2b7098"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "fd586fb88f79c4af96d1bf5c9e3453b8412eedf523aa3d176836f9b0447b8a74"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.2+0/snappy.v1.2.2.aarch64-linux-musl-cxx03.tar.gz"
[[snappy]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c691191eec013b7219ea43d616e6cb6031f4a0bc"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "1820b131879c5bbffd714f4ba049f9a65480966c4e767c6225b3b3c6fb6b8bd3"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.2+0/snappy.v1.2.2.aarch64-linux-musl-cxx11.tar.gz"
[[snappy]]
arch = "aarch64"
git-tree-sha1 = "d71861abc0c825176ddbf05f5905144a2e1d16f6"
os = "freebsd"

    [[snappy.download]]
    sha256 = "b0da6260c700465131a61a4aa2a5b571d2212614ed819ed8e47106b446fd79bc"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.2+0/snappy.v1.2.2.aarch64-unknown-freebsd.tar.gz"
[[snappy]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "718b660168e4c37959778f1da6915f8f8efb5d01"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "bee444d447bba1c6e5f66836e1703ab6e6baac8b26d46ca0b47fa1d387b62440"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.2+0/snappy.v1.2.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[snappy]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5aff6020a1b7f2cc6bc07c4e0ef006c3c2d39ee8"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "ae176ac38cda89fcec752493c8dcb7ed2889708b6ff7259c4cd9b3b6880ddb11"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.2+0/snappy.v1.2.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[snappy]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0c4a46dc345798d892e4f47556e7dda65f234dec"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "c4606d506075abddc80ed59bfb8f230854a05f9c94d6bbdd498518aeb685b3bf"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.2+0/snappy.v1.2.2.armv6l-linux-musleabihf-cxx03.tar.gz"
[[snappy]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b6562cc57acc9331021fc9f8ccccb9ba3bd73459"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "8edcd2ec48bfb62de618ce666fea5ddd44d57d6971dd1db405c7ba7c7426e359"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.2+0/snappy.v1.2.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[snappy]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b00189bfcc2f29f149abafeab2a12ea049ea5bf3"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "86840d19b1b19cea2472d0332bb29e969a177e1b84c7d17cb3c450051aee450a"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.2+0/snappy.v1.2.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[snappy]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8345f96b14013c40bb25e70c60d3a30e531fd5ba"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "916ff56857e55b54898f1627dcb7057d7e2aea05387a2ec4f43bf6453599fe87"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.2+0/snappy.v1.2.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[snappy]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "402cfa466398613cd729adc14f842fe8855d9753"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "1ef36a8d8e0f5fa029ad70602db66fda3ad5903656a21199a0d0611360efdb25"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.2+0/snappy.v1.2.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[snappy]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "77c67746538a328d953ed9fd863881cf45db1d17"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "bb206e42b807a3d3a3b1bf9d7712981bf7204b792787f38c237ba5d862b3b1c4"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.2+0/snappy.v1.2.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[snappy]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "15032c041194893bdee0b4179e9d863bb1fa2e0b"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "9d1d52809349b4e501bbcf4e15bdac97877d697c50f34dea3fbc5ecfe239e35f"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.2+0/snappy.v1.2.2.i686-linux-gnu-cxx03.tar.gz"
[[snappy]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e509b7f184b01116c47edf60f5e8cd4166ed1f79"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "9c8663412ef4b5d503afb28995b90dd3d1bdb10b9ce8fa15d5b2c8002ea2f187"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.2+0/snappy.v1.2.2.i686-linux-gnu-cxx11.tar.gz"
[[snappy]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9e4e9ff363e06b74276032fdddfba979dd06b6d5"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "21c7b27a0885a96442f7966b2b9470a8f4afdbf77ed05e5d5a5fb07d91596322"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.2+0/snappy.v1.2.2.i686-linux-musl-cxx03.tar.gz"
[[snappy]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dcf73bd3d03037dbdc5adb31ade5edbe146ab1b7"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "e6b8667817d8caf0aea24679226afd55091c2d174cf337c7043776f5844b729a"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.2+0/snappy.v1.2.2.i686-linux-musl-cxx11.tar.gz"
[[snappy]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "07f7f2ab11704e359079bbd645357302ba0b31b9"
os = "windows"

    [[snappy.download]]
    sha256 = "733cf0ec117d78297e867b57fe3a27ec71891c99a781aec3d844b50096885aa6"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.2+0/snappy.v1.2.2.i686-w64-mingw32-cxx03.tar.gz"
[[snappy]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "651a5d58e535b4b0f4f31d20d6b4e6f6e465a358"
os = "windows"

    [[snappy.download]]
    sha256 = "385add3ddd11bd69e66e64d63e7ba3b1c6dc3dc404bd257c6f78def28567109b"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.2+0/snappy.v1.2.2.i686-w64-mingw32-cxx11.tar.gz"
[[snappy]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "83815fcf5848729e3b50264b777a600fe3700bea"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "311ce3460d47b0b871de67de9f5db175628fe48312ea93df0415840f68107dcb"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.2+0/snappy.v1.2.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[snappy]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "29d434d82fb26dc83e14aded39974688e7ee494b"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "2f934343d8892a68860279e064a901b7b52fe89d1543de02d6de78522060718d"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.2+0/snappy.v1.2.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[snappy]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5a3bd2eca9339e5decfd9ff230f423eea42b02b7"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "3b9403bda1c04f57406b4dfab55bcd29b23a11e9007e0aa65af7907196b9a70c"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.2+0/snappy.v1.2.2.riscv64-linux-gnu-cxx03.tar.gz"
[[snappy]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e671f8f339e5189bb479a46a4d25efaf374bfc06"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "41660dab9ab9ce670cee2e8c040ae9c358105e1f9134b6762a23fd4a9fa114cc"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.2+0/snappy.v1.2.2.riscv64-linux-gnu-cxx11.tar.gz"
[[snappy]]
arch = "x86_64"
git-tree-sha1 = "d5b9236d528e5badfc49fb777a4d86d9fff7b4ea"
os = "macos"

    [[snappy.download]]
    sha256 = "b78ac4bc1c284389150460ec60b94183945d3caf0a14e1b44cda00895221e3ca"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.2+0/snappy.v1.2.2.x86_64-apple-darwin.tar.gz"
[[snappy]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3ddf28f98152798f8ee646e745242328b536b9f8"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "0cc3be6ea51f832ac259b0e42cf15ffe0272047360005055572649c6dfc7c079"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.2+0/snappy.v1.2.2.x86_64-linux-gnu-cxx03.tar.gz"
[[snappy]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eeb4457626799d32bcad9f488bfef72b7e9151c6"
libc = "glibc"
os = "linux"

    [[snappy.download]]
    sha256 = "52b43a1e9f5ba9192189767e44fff373b69500d296bc98dba08f805c49d1edf3"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.2+0/snappy.v1.2.2.x86_64-linux-gnu-cxx11.tar.gz"
[[snappy]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b850e0749e9c09f2ea2cfa49889fc109665127b0"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "02139f32d037b3825b37ece0bc169ceee54c723c24b8c6693f312738545dd2c1"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.2+0/snappy.v1.2.2.x86_64-linux-musl-cxx03.tar.gz"
[[snappy]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a10a6e2bcb500cab5b2a4bfaf2b52bf9f90a14bb"
libc = "musl"
os = "linux"

    [[snappy.download]]
    sha256 = "8c9b8b265c09e7deb05248bed8c90d0ac9264f584b6a01292f4a0f7b5e5d5798"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.2+0/snappy.v1.2.2.x86_64-linux-musl-cxx11.tar.gz"
[[snappy]]
arch = "x86_64"
git-tree-sha1 = "253f6f03ec655a296527119d1af045978c8023a2"
os = "freebsd"

    [[snappy.download]]
    sha256 = "bf47a1ff40755c119132cfc4ee7d446476056517f6fe80aab1a3aae65361324f"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.2+0/snappy.v1.2.2.x86_64-unknown-freebsd.tar.gz"
[[snappy]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f4545673c6289a2e234008d3f3bd02fa591b89df"
os = "windows"

    [[snappy.download]]
    sha256 = "f578f354d13cf083b7046c0bb5ba4533e958ce7ac98a3515e2c933487764f1e3"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.2+0/snappy.v1.2.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[snappy]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2ab77436ec541773d2e7cf754ab3e86fa4623de3"
os = "windows"

    [[snappy.download]]
    sha256 = "aa78d5193167b54b609f61e9dc6c4ec8d18d68f1443232fac916b603248829cd"
    url = "https://github.com/JuliaBinaryWrappers/snappy_jll.jl/releases/download/snappy-v1.2.2+0/snappy.v1.2.2.x86_64-w64-mingw32-cxx11.tar.gz"
