# Autogenerated wrapper script for snappy_jll for i686-w64-mingw32-cxx11
export libsnappy

using LZO_jll
using Lz4_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("snappy")
JLLWrappers.@declare_library_product(libsnappy, "libsnappy.dll")
function __init__()
    JLLWrappers.@generate_init_header(LZO_jll, Lz4_jll, Zlib_jll)
    JLLWrappers.@init_library_product(
        libsnappy,
        "bin\\libsnappy.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
